keycloak:
  hostname: keycloak
  image: adamcrow64/keycloak-1.9.1 
  environment:
    - KEYCLOAK_USER=admin 
    - KEYCLOAK_PASSWORD=my_password
  links:
    - keycloakdb:db
  ports:
    - 48443:8443
    - 48080:8080

keycloakdb:
  image: mysql 
  environment:
    - MYSQL_DATABASE=keycloakdb
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=my_password
    - MYSQL_ROOT_PASSWORD=my_password
